version: "3"

services:
  kernel:
    container_name: kernel
    image: merakianalytics/kernel:mongo
    ports:
      - 8080:8080
    env_file:
      - ./.env
    restart: always
    networks:
      - kernel
    depends_on:
      - mongo
  swagger:
    container_name: kernel_swagger
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    environment:
      - API_URL=http://localhost:8080/lol/swagger.json
    restart: always
    networks:
      - kernel
    depends_on:
      - kernel
  mongo:
    container_name: mongo
    image: mongo:jessie
    restart: always
    networks:
      - kernel
  graphql:
    container_name: graphql
    build: .
    ports:
      - 5000:5000
    environment:
      - KERNEL_URL=http://kernel:8080
    networks:
      - kernel
    depends_on:
      - kernel

networks:
  kernel:
    driver: bridge
